# Generated by Django 5.2.17 on 2026-10-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='When off, an issue above the stock on hand is blocked (BR-02, BR-09)'),
        ),
        migrations.AddField(
            model_name='company',
            name='po_approval_limit',
            field=models.DecimalField(decimal_places=2, default=50000, help_text="A purchase order above this value needs the owner's approval (BR-19). 0 = every PO needs approval.", max_digits=14),
        ),
        migrations.AddField(
            model_name='company',
            name='valuation_method',
            field=models.CharField(choices=[('weighted_average', 'Weighted average per item per factory'), ('specific_roll', 'Specific cost per fabric roll (other items: weighted average)')], default='weighted_average', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='allow_negative_stock',
            field=models.BooleanField(default=False, help_text='When off, an issue above the stock on hand is blocked (BR-02, BR-09)'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='po_approval_limit',
            field=models.DecimalField(decimal_places=2, default=50000, help_text="A purchase order above this value needs the owner's approval (BR-19). 0 = every PO needs approval.", max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='valuation_method',
            field=models.CharField(choices=[('weighted_average', 'Weighted average per item per factory'), ('specific_roll', 'Specific cost per fabric roll (other items: weighted average)')], default='weighted_average', max_length=20),
        ),
    ]
