# Generated by Django 5.2.17 on 2026-10-03 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_allow_negative_stock_and_more'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="For a fabricator's premises: whose it is", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.party'),
        ),
        migrations.AddField(
            model_name='location',
            name='party',
            field=models.ForeignKey(blank=True, help_text="For a fabricator's premises: whose it is", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='masters.party'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='loc_type',
            field=models.CharField(choices=[('godown', 'Godown'), ('cutting', 'Cutting floor'), ('process', 'Process area'), ('showroom', 'Showroom'), ('dispatch', 'Dispatch'), ('transit', 'In transit'), ('fabricator', 'At a fabricator / subcontractor'), ('rejects', 'Rejects')], max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_type',
            field=models.CharField(choices=[('godown', 'Godown'), ('cutting', 'Cutting floor'), ('process', 'Process area'), ('showroom', 'Showroom'), ('dispatch', 'Dispatch'), ('transit', 'In transit'), ('fabricator', 'At a fabricator / subcontractor'), ('rejects', 'Rejects')], max_length=10),
        ),
    ]
