# Generated by Django 5.2.17 on 2026-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicallocation_party_location_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bom_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Fabric used beyond this many percent over or under the BOM is flagged (BR-10)', max_digits=5, verbose_name='BOM variance tolerance %'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='bom_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Fabric used beyond this many percent over or under the BOM is flagged (BR-10)', max_digits=5, verbose_name='BOM variance tolerance %'),
        ),
    ]
