# Generated by Django 5.2.17 on 2026-10-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_bom_tolerance_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_factory',
            field=models.ForeignKey(blank=True, help_text='The factory this user was last working in; selected again at next login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.factory'),
        ),
    ]
