# Generated by Django 5.2.17 on 2026-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_last_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pieces_per_box',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pieces packed in one box, unless the style says otherwise. 0 = boxes are not counted.'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='pieces_per_box',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pieces packed in one box, unless the style says otherwise. 0 = boxes are not counted.'),
        ),
    ]
