# Generated by Django 5.2.17 on 2026-10-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pieces_per_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bom_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Pieces cut more than this many percent over or under the estimate made when the fabric was issued are flagged (BR-10)', max_digits=5, verbose_name='Cutting variance tolerance %'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='bom_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Pieces cut more than this many percent over or under the estimate made when the fabric was issued are flagged (BR-10)', max_digits=5, verbose_name='Cutting variance tolerance %'),
        ),
    ]
