# Generated by Django 5.2.17 on 2026-10-03 06:57

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('statement', models.CharField(choices=[('bs', 'Balance sheet'), ('pl', 'Profit & loss')], max_length=2)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_groups', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.accountgroup')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccountGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('statement', models.CharField(choices=[('bs', 'Balance sheet'), ('pl', 'Profit & loss')], max_length=2)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.accountgroup')),
            ],
            options={
                'verbose_name': 'historical account group',
                'verbose_name_plural': 'historical account groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLedger',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('system_key', models.CharField(blank=True, help_text='Stable handle code uses to find this ledger even if it is renamed', max_length=40, null=True)),
                ('bill_wise', models.BooleanField(default=False, help_text='Track outstanding bill by bill')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.accountgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ledger',
                'verbose_name_plural': 'historical ledgers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('system_key', models.CharField(blank=True, help_text='Stable handle code uses to find this ledger even if it is renamed', max_length=40, null=True)),
                ('bill_wise', models.BooleanField(default=False, help_text='Track outstanding bill by bill')),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='core.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='ledger.accountgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('debit_note', 'Debit note'), ('credit_note', 'Credit note'), ('stock_journal', 'Stock journal'), ('job_work_bill', 'Job work bill'), ('payroll', 'Payroll'), ('opening', 'Opening balance')], max_length=20)),
                ('number', models.CharField(blank=True, help_text='Assigned when posted', max_length=50, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=6)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, help_text='app_label.model of the source document', max_length=60)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='core.financialyear')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVoucherLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.ledger')),
                ('voucher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher')),
            ],
            options={
                'verbose_name': 'historical voucher line',
                'verbose_name_plural': 'historical voucher lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVoucher',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('contra', 'Contra'), ('journal', 'Journal'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('debit_note', 'Debit note'), ('credit_note', 'Credit note'), ('stock_journal', 'Stock journal'), ('job_work_bill', 'Job work bill'), ('payroll', 'Payroll'), ('opening', 'Opening balance')], max_length=20)),
                ('number', models.CharField(blank=True, help_text='Assigned when posted', max_length=50, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=6)),
                ('narration', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(blank=True, help_text='app_label.model of the source document', max_length=60)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('financial_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.financialyear')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher')),
            ],
            options={
                'verbose_name': 'historical voucher',
                'verbose_name_plural': 'historical vouchers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.voucher')),
            ],
            options={
                'ordering': ['voucher_id', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBillAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('new', 'New reference'), ('against', 'Against reference'), ('advance', 'Advance'), ('on_account', 'On account')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucherline')),
            ],
            options={
                'verbose_name': 'historical bill allocation',
                'verbose_name_plural': 'historical bill allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(choices=[('new', 'New reference'), ('against', 'Against reference'), ('advance', 'Advance'), ('on_account', 'On account')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.voucherline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_group_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_ledger_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('company', 'system_key'), name='uniq_ledger_system_key'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_vouc_source__48010d_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'number'), name='uniq_voucher_number'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('number__isnull', False), _connector='OR'), name='posted_voucher_has_number'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='voucher_reversed_once'),
        ),
        migrations.AddConstraint(
            model_name='voucherline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='line_exactly_one_side'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_positive'),
        ),
    ]
