# Generated by Django 5.2.17 on 2026-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvoucher',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Vendor invoice no.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Vendor invoice no.'),
        ),
    ]
