# Generated by Django 5.2.17 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='no_loss',
            field=models.BooleanField(default=False, help_text='Pieces out must equal pieces in when this is done in-house (e.g. ironing)', verbose_name='No loss allowed'),
        ),
        migrations.AddField(
            model_name='process',
            name='no_loss',
            field=models.BooleanField(default=False, help_text='Pieces out must equal pieces in when this is done in-house (e.g. ironing)', verbose_name='No loss allowed'),
        ),
    ]
