# Generated by Django 5.2.17 on 2026-10-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_ironing_no_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstyle',
            name='pieces_per_box',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Pieces packed in one box. Blank = the company's setting.", null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='pieces_per_box',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Pieces packed in one box. Blank = the company's setting.", null=True),
        ),
    ]
