# Generated by Django 5.2.17 on 2026-10-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_pieces_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomline',
            name='process',
            field=models.ForeignKey(blank=True, help_text='The process that uses this material. Blank = stitching for trims, packing for packing material.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.process', verbose_name='Used in'),
        ),
    ]
