# Generated by Django 5.2.17 on 2026-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_ironing_no_loss'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingentry',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the BOM says the fabric burnt should give', null=True),
        ),
        migrations.AddField(
            model_name='cuttingsize',
            name='loss',
            field=models.PositiveIntegerField(default=0, help_text='Pieces cut but lost or spoiled before bundling'),
        ),
        migrations.AddField(
            model_name='fabricissue',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the BOM says this fabric should give', null=True),
        ),
        migrations.AddField(
            model_name='historicalcuttingentry',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the BOM says the fabric burnt should give', null=True),
        ),
        migrations.AddField(
            model_name='historicalfabricissue',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the BOM says this fabric should give', null=True),
        ),
        migrations.AddConstraint(
            model_name='cuttingsize',
            constraint=models.CheckConstraint(condition=models.Q(('loss__lte', models.F('pieces'))), name='cutting_loss_within_pieces'),
        ),
    ]
