# Generated by Django 5.2.17 on 2026-10-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_cutting_loss_expected_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='split_from',
            field=models.ForeignKey(blank=True, help_text='The bundle these pieces were taken out of (rework sent back at QC)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='production.bundle'),
        ),
        migrations.AddField(
            model_name='historicalbundle',
            name='split_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The bundle these pieces were taken out of (rework sent back at QC)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.bundle'),
        ),
    ]
