# Generated by Django 5.2.17 on 2026-10-06 14:56

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cutting_variance_label'),
        ('ledger', '0002_voucher_vendor_invoice_no'),
        ('masters', '0005_bomline_process'),
        ('production', '0004_pieces_per_box'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingentry',
            name='expected_fabric',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='No longer filled: the cutting is compared in pieces', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='cuttingentry',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces estimated for the fabric this lay burnt', null=True),
        ),
        migrations.AlterField(
            model_name='cuttingentry',
            name='variance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pieces cut against the estimate, in percent', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='fabricissue',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the cutting master expects from this fabric', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcuttingentry',
            name='expected_fabric',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='No longer filled: the cutting is compared in pieces', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcuttingentry',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces estimated for the fabric this lay burnt', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcuttingentry',
            name='variance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pieces cut against the estimate, in percent', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfabricissue',
            name='expected_pieces',
            field=models.PositiveIntegerField(blank=True, help_text='Pieces the cutting master expects from this fabric', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalStepMaterialIssue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('pieces', models.PositiveIntegerField(default=0, help_text='Pieces in the bundles these materials were issued for')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot')),
                ('step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lotstep')),
                ('voucher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher')),
            ],
            options={
                'verbose_name': 'historical step material issue',
                'verbose_name_plural': 'historical step material issues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StepMaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pieces', models.PositiveIntegerField(default=0, help_text='Pieces in the bundles these materials were issued for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='production.lot')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='production.lotstep')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StepMaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost when issued', max_digits=16)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.stepmaterialissue')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.material')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issue', 'material'), name='uniq_step_issue_material'), models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='step_issue_qty_positive')],
            },
        ),
    ]
