# Generated by Django 5.2.17 on 2026-10-07 06:36

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cutting_variance_label'),
        ('production', '0005_step_material_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'base_manager_name': 'all_objects', 'ordering': ['lot', 'bundle_no']},
        ),
        migrations.AlterModelManagers(
            name='bundle',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='voided',
            field=models.BooleanField(default=False, help_text='The step that made this bundle was undone'),
        ),
        migrations.AddField(
            model_name='historicalbundle',
            name='voided',
            field=models.BooleanField(default=False, help_text='The step that made this bundle was undone'),
        ),
        migrations.CreateModel(
            name='HistoricalProductionAction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fabric', 'Fabric issued'), ('cutting', 'Cutting recorded'), ('bundles', 'Bundles made'), ('move', 'Bundles moved'), ('count', 'Pieces taken out'), ('split', 'Bundle split'), ('pack', 'Packed'), ('challan', 'Sent to fabricator'), ('receipt', 'Received from fabricator'), ('approval', 'Over-receipt approved'), ('qc', 'QC recorded')], max_length=10)),
                ('date', models.DateField(help_text='Date of the step')),
                ('summary', models.CharField(max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=60)),
                ('doc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('undone', models.BooleanField(default=False)),
                ('undo_reason', models.CharField(blank=True, max_length=255)),
                ('undo_date', models.DateField(blank=True, help_text='Date the reversing entries carry', null=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot')),
                ('undone_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical production action',
                'verbose_name_plural': 'historical production actions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fabric', 'Fabric issued'), ('cutting', 'Cutting recorded'), ('bundles', 'Bundles made'), ('move', 'Bundles moved'), ('count', 'Pieces taken out'), ('split', 'Bundle split'), ('pack', 'Packed'), ('challan', 'Sent to fabricator'), ('receipt', 'Received from fabricator'), ('approval', 'Over-receipt approved'), ('qc', 'QC recorded')], max_length=10)),
                ('date', models.DateField(help_text='Date of the step')),
                ('summary', models.CharField(max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=60)),
                ('doc_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone', models.BooleanField(default=False)),
                ('undo_reason', models.CharField(blank=True, max_length=255)),
                ('undo_date', models.DateField(blank=True, help_text='Date the reversing entries carry', null=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='production.lot')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('movement', 'Stock movement'), ('voucher', 'Voucher'), ('cost', 'Lot cost'), ('created', 'Row created'), ('changed', 'Row changed')], max_length=8)),
                ('model', models.CharField(max_length=60)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='productionaction',
            index=models.Index(fields=['doc_type', 'doc_id'], name='production__doc_typ_e0b70d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionactionitem',
            index=models.Index(fields=['model', 'object_id'], name='production__model_3ea96a_idx'),
        ),
    ]
