# Generated by Django 5.2.17 on 2026-10-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_last_factory'),
        ('masters', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='is_direct',
            field=models.BooleanField(default=False, help_text='Booked without a GRN: posting also brings the goods into stock at the location', verbose_name='Direct purchase'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoice',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Direct purchase: where the goods are received', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.material'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseinvoiceline',
            name='sku',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.sku'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_direct',
            field=models.BooleanField(default=False, help_text='Booked without a GRN: posting also brings the goods into stock at the location', verbose_name='Direct purchase'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Direct purchase: where the goods are received', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.location'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.material'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sku'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='grn_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='purchases.grnline'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grn_line__isnull', False), ('material__isnull', True), ('sku__isnull', True)), models.Q(('grn_line__isnull', True), ('material__isnull', False), ('sku__isnull', True)), models.Q(('grn_line__isnull', True), ('material__isnull', True), ('sku__isnull', False)), _connector='OR'), name='pi_line_grn_or_one_item'),
        ),
    ]
