# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.bundle'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.lot'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('return_out', 'Return to vendor'), ('revaluation', 'Value adjustment'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('production', 'Production output'), ('loss', 'Loss / write-off')], max_length=14),
        ),
    ]
