# Generated by Django 5.2.17 on 2026-10-03 14:32

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_bom_tolerance_pct_and_more'),
        ('inventory', '0002_stockmovement_bundle_stockmovement_lot_and_more'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockAlert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, help_text='The minimum when the alert was raised', max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('qty_at_alert', models.DecimalField(decimal_places=3, max_digits=16)),
                ('raised_at', models.DateTimeField(blank=True, editable=False)),
                ('cleared_at', models.DateTimeField(blank=True, help_text='Stock recovered to the minimum', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acknowledged_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.material')),
                ('style', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.style')),
            ],
            options={
                'verbose_name': 'historical stock alert',
                'verbose_name_plural': 'historical stock alerts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, help_text='The minimum when the alert was raised', max_digits=14)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('qty_at_alert', models.DecimalField(decimal_places=3, max_digits=16)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, help_text='Stock recovered to the minimum', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.material')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.style')),
            ],
            options={
                'ordering': ['-raised_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('style__isnull', True)), models.Q(('material__isnull', True), ('style__isnull', False)), _connector='OR'), name='stockalert_one_item')],
            },
        ),
    ]
