# Generated by Django 5.2.17 on 2026-10-03 16:44

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_bom_tolerance_pct_and_more'),
        ('inventory', '0003_stockalert'),
        ('ledger', '0002_voucher_vendor_invoice_no'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockJournal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('count', 'Stock count correction'), ('damage', 'Damage or write-off'), ('conversion', 'Repacking or conversion'), ('other', 'Other')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=10)),
                ('value_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('value_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
                ('voucher', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher')),
            ],
            options={
                'verbose_name': 'historical stock journal',
                'verbose_name_plural': 'historical stock journals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('count', 'Stock count correction'), ('damage', 'Damage or write-off'), ('conversion', 'Repacking or conversion'), ('other', 'Other')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=10)),
                ('value_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('value_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.location')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStockJournalLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Taken out'), ('in', 'Brought in')], max_length=3)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Brought-in lines only', max_digits=14, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set when posted', max_digits=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.material')),
                ('roll', models.ForeignKey(blank=True, db_constraint=False, help_text='Fabric: the roll taken out, or the new roll brought in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.fabricroll')),
                ('sku', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.sku')),
                ('journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockjournal')),
            ],
            options={
                'verbose_name': 'historical stock journal line',
                'verbose_name_plural': 'historical stock journal lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('out', 'Taken out'), ('in', 'Brought in')], max_length=3)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Brought-in lines only', max_digits=14, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set when posted', max_digits=16)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockjournal')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.material')),
                ('roll', models.ForeignKey(blank=True, help_text='Fabric: the roll taken out, or the new roll brought in', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.fabricroll')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sku')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockjournal',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'number'), name='uniq_stockjournal_number'),
        ),
        migrations.AddConstraint(
            model_name='stockjournalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('sku__isnull', True)), models.Q(('material__isnull', True), ('sku__isnull', False)), _connector='OR'), name='stockjournalline_one_item'),
        ),
        migrations.AddConstraint(
            model_name='stockjournalline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='stockjournalline_qty_positive'),
        ),
    ]
