# Generated by Django 5.2.17 on 2026-10-03 06:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTaxSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gst', 'GST'), ('tds', 'TDS')], max_length=3)),
                ('enabled', models.BooleanField()),
                ('effective_from', models.DateField()),
                ('registration_number', models.CharField(blank=True, help_text='GSTIN when GST is on, TAN when TDS is on', max_length=15, verbose_name='GSTIN / TAN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tax setting',
                'verbose_name_plural': 'historical tax settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gst', 'GST'), ('tds', 'TDS')], max_length=3)),
                ('enabled', models.BooleanField()),
                ('effective_from', models.DateField()),
                ('registration_number', models.CharField(blank=True, help_text='GSTIN when GST is on, TAN when TDS is on', max_length=15, verbose_name='GSTIN / TAN')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_settings', to='core.company')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.factory')),
            ],
            options={
                'ordering': ['kind', 'factory_id', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('company', 'factory', 'kind', 'effective_from'), name='uniq_tax_setting_per_date')],
            },
        ),
    ]
