# Generated by Django 5.2.17 on 2026-10-03 07:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HSN code',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHSN',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical HSN code',
                'verbose_name_plural': 'historical HSN codes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHsnSlab',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value_from', models.DecimalField(decimal_places=2, default=0, help_text='Per piece, inclusive', max_digits=12)),
                ('value_to', models.DecimalField(blank=True, decimal_places=2, help_text='Per piece, inclusive; blank = no limit', max_digits=12, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %')),
                ('effective_from', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hsn', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.hsn')),
            ],
            options={
                'verbose_name': 'historical hsn slab',
                'verbose_name_plural': 'historical hsn slabs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HsnSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_from', models.DecimalField(decimal_places=2, default=0, help_text='Per piece, inclusive', max_digits=12)),
                ('value_to', models.DecimalField(blank=True, decimal_places=2, help_text='Per piece, inclusive; blank = no limit', max_digits=12, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %')),
                ('effective_from', models.DateField()),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='tax.hsn')),
            ],
            options={
                'ordering': ['hsn__code', '-effective_from', 'value_from'],
            },
        ),
    ]
