# Generated by Django 5.2.17 on 2026-10-03 08:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_hsn_historicalhsn_historicalhsnslab_hsnslab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('gst', 'GST'), ('tds', 'TDS'), ('tcs', 'TCS')], max_length=3)),
                ('is_interstate', models.BooleanField(default=False, help_text='GST only: IGST instead of CGST + SGST')),
                ('is_reverse_charge', models.BooleanField(default=False, help_text='GST only: the buyer pays the tax (RCM)')),
                ('section', models.CharField(blank=True, help_text='TDS / TCS section, for example 194C', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTaxTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('kind', models.CharField(choices=[('gst', 'GST'), ('tds', 'TDS'), ('tcs', 'TCS')], max_length=3)),
                ('is_interstate', models.BooleanField(default=False, help_text='GST only: IGST instead of CGST + SGST')),
                ('is_reverse_charge', models.BooleanField(default=False, help_text='GST only: the buyer pays the tax (RCM)')),
                ('section', models.CharField(blank=True, help_text='TDS / TCS section, for example 194C', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tax template',
                'verbose_name_plural': 'historical tax templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxTemplateLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('component', models.CharField(choices=[('cgst', 'CGST'), ('sgst', 'SGST'), ('igst', 'IGST'), ('tds', 'TDS'), ('tcs', 'TCS')], max_length=4)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rate %')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.taxtemplate')),
            ],
            options={
                'verbose_name': 'historical tax template line',
                'verbose_name_plural': 'historical tax template lines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TaxTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('cgst', 'CGST'), ('sgst', 'SGST'), ('igst', 'IGST'), ('tds', 'TDS'), ('tcs', 'TCS')], max_length=4)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rate %')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tax.taxtemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'component'), name='uniq_template_component')],
            },
        ),
    ]
