# Generated by Django 5.2.17 on 2026-10-03 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_company_bom_tolerance_pct_and_more'),
        ('jobwork', '0001_initial'),
        ('ledger', '0001_initial'),
        ('masters', '0001_initial'),
        ('production', '0001_initial'),
        ('tax', '0003_taxtemplate_historicaltaxtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challanbundle',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challan_lines', to='production.bundle'),
        ),
        migrations.AddField(
            model_name='challantrim',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.material'),
        ),
        migrations.AddField(
            model_name='historicalchallanbundle',
            name='bundle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.bundle'),
        ),
        migrations.AddField(
            model_name='historicalchallanbundle',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.party'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='tds_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.taxtemplate'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbill',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbillline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkbillline',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.party'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lotstep'),
        ),
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='voucher',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.voucher'),
        ),
        migrations.AddField(
            model_name='historicallabourrate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallabourrate',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.party'),
        ),
        migrations.AddField(
            model_name='historicallabourrate',
            name='process',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.process'),
        ),
        migrations.AddField(
            model_name='historicalqcresult',
            name='checked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalqcresult',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='factory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location'),
        ),
        migrations.AddField(
            model_name='historicalreceiptline',
            name='challan_bundle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.challanbundle'),
        ),
        migrations.AddField(
            model_name='historicalreceiptline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_bills', to='masters.party'),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='tds_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.taxtemplate'),
        ),
        migrations.AddField(
            model_name='jobworkbill',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.voucher'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbillline',
            name='bill',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkbill'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='bill',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkbill'),
        ),
        migrations.AddField(
            model_name='jobworkbilldeduction',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_lines', to='jobwork.jobworkbill'),
        ),
        migrations.AddField(
            model_name='jobworkbilldeduction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.lot'),
        ),
        migrations.AddField(
            model_name='jobworkbillline',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jobwork.jobworkbill'),
        ),
        migrations.AddField(
            model_name='jobworkbillline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.lot'),
        ),
        migrations.AddField(
            model_name='historicalqcresult',
            name='bill_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkbillline'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='production.lot'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='masters.party'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='production.lotstep'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ledger.voucher'),
        ),
        migrations.AddField(
            model_name='jobworkbillline',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='jobworkbilldeduction',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='historicalreceipt',
            name='challan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbillline',
            name='challan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='challan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='historicalchallanbundle',
            name='challan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='challantrim',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='challanbundle',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='labourrate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labour_rates', to='masters.party'),
        ),
        migrations.AddField(
            model_name='labourrate',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.process'),
        ),
        migrations.AddField(
            model_name='labourrateaddon',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='jobwork.labourrate'),
        ),
        migrations.AddField(
            model_name='labourratesize',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='jobwork.labourrate'),
        ),
        migrations.AddField(
            model_name='labourratesize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.size'),
        ),
        migrations.AddField(
            model_name='qcresult',
            name='bill_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_results', to='jobwork.jobworkbillline'),
        ),
        migrations.AddField(
            model_name='qcresult',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='challan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='jobwork.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.location'),
        ),
        migrations.AddField(
            model_name='historicalreceiptline',
            name='receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receipt'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='challan_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='jobwork.challanbundle'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='jobwork.receipt'),
        ),
        migrations.AddField(
            model_name='qcresult',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qc', to='jobwork.receiptline'),
        ),
        migrations.AddField(
            model_name='jobworkbilldeduction',
            name='source_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobwork.receiptline'),
        ),
        migrations.AddField(
            model_name='historicalqcresult',
            name='line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receiptline'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='source_receipt_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receiptline'),
        ),
        migrations.AddField(
            model_name='receipttrim',
            name='challan_trim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='jobwork.challantrim'),
        ),
        migrations.AddField(
            model_name='receipttrim',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='jobwork.receipt'),
        ),
        migrations.AddField(
            model_name='jobworkbilldeduction',
            name='source_receipt_trim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobwork.receipttrim'),
        ),
        migrations.AddField(
            model_name='historicaljobworkbilldeduction',
            name='source_receipt_trim',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receipttrim'),
        ),
        migrations.AddConstraint(
            model_name='jobworkbill',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'number'), name='uniq_jw_bill_number'),
        ),
        migrations.AddConstraint(
            model_name='jobworkchallan',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'number'), name='uniq_challan_number'),
        ),
        migrations.AddConstraint(
            model_name='challantrim',
            constraint=models.CheckConstraint(condition=models.Q(('qty_issued__gt', 0)), name='challan_trim_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='challanbundle',
            constraint=models.UniqueConstraint(fields=('challan', 'bundle'), name='uniq_challan_bundle'),
        ),
        migrations.AddConstraint(
            model_name='challanbundle',
            constraint=models.CheckConstraint(condition=models.Q(('qty_issued__gt', 0)), name='challan_bundle_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='labourrate',
            constraint=models.UniqueConstraint(fields=('party', 'process', 'effective_from'), name='uniq_labour_rate_date'),
        ),
        migrations.AddConstraint(
            model_name='labourrate',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gte', 0), ('flat_amount__gte', 0), ('rework_rate__gte', 0)), name='labour_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='labourrateaddon',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='addon_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='labourratesize',
            constraint=models.UniqueConstraint(fields=('rate', 'size'), name='uniq_rate_size'),
        ),
        migrations.AddConstraint(
            model_name='labourratesize',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='rate_size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'number'), name='uniq_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='qcresult',
            constraint=models.CheckConstraint(condition=models.Q(('accepted__gte', 0)), name='qc_accepted_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobworkbilldeduction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='deduction_positive'),
        ),
    ]
