# Generated by Django 5.2.17 on 2026-10-03 14:34

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_bom_tolerance_pct_and_more'),
        ('jobwork', '0002_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.factory')),
            ],
            options={
                'ordering': ['-date', 'factory__code'],
            },
        ),
        migrations.CreateModel(
            name='DailySummaryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_bundles', models.PositiveIntegerField(default=0)),
                ('issued_pcs', models.PositiveIntegerField(default=0)),
                ('received_pcs', models.PositiveIntegerField(default=0)),
                ('accepted_pcs', models.PositiveIntegerField(default=0)),
                ('pending_pcs', models.PositiveIntegerField(default=0, help_text='Still with the fabricator at the end of the day')),
                ('overdue_pcs', models.PositiveIntegerField(default=0, help_text='Pending on challans past their expected date')),
                ('earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accepted pieces x rate, today', max_digits=16)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.party')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='jobwork.dailysummary')),
            ],
            options={
                'ordering': ['party__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDailySummary',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('factory', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.factory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical daily summary',
                'verbose_name_plural': 'historical daily summarys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDailySummaryRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('issued_bundles', models.PositiveIntegerField(default=0)),
                ('issued_pcs', models.PositiveIntegerField(default=0)),
                ('received_pcs', models.PositiveIntegerField(default=0)),
                ('accepted_pcs', models.PositiveIntegerField(default=0)),
                ('pending_pcs', models.PositiveIntegerField(default=0, help_text='Still with the fabricator at the end of the day')),
                ('overdue_pcs', models.PositiveIntegerField(default=0, help_text='Pending on challans past their expected date')),
                ('earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accepted pieces x rate, today', max_digits=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.party')),
                ('summary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.dailysummary')),
            ],
            options={
                'verbose_name': 'historical daily summary row',
                'verbose_name_plural': 'historical daily summary rows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='dailysummary',
            constraint=models.UniqueConstraint(fields=('factory', 'date'), name='uniq_daily_summary'),
        ),
        migrations.AddConstraint(
            model_name='dailysummaryrow',
            constraint=models.UniqueConstraint(fields=('summary', 'party'), name='uniq_summary_party'),
        ),
    ]
