# Generated by Django 5.2.17 on 2026-10-06 11:44

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobwork', '0003_dailysummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobworkchallan',
            name='pay_basis',
            field=models.CharField(choices=[('accepted', 'Pieces accepted at QC'), ('received', 'Pieces received back')], default='accepted', help_text='Fixed from the labour rate when the challan is made', max_length=8),
        ),
        migrations.AddField(
            model_name='historicallabourrate',
            name='pay_basis',
            field=models.CharField(choices=[('accepted', 'Pieces accepted at QC'), ('received', 'Pieces received back')], default='accepted', help_text='Accepted: only pieces that pass QC are paid. Received: every piece that comes back is paid, rejected or not, and rework is paid at the rework rate alone.', max_length=8, verbose_name='Pay on'),
        ),
        migrations.AddField(
            model_name='historicalqcresult',
            name='pay_qty',
            field=models.PositiveIntegerField(default=0, help_text="Pieces to pay for, fixed at QC from the challan's pay basis"),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='pay_basis',
            field=models.CharField(choices=[('accepted', 'Pieces accepted at QC'), ('received', 'Pieces received back')], default='accepted', help_text='Fixed from the labour rate when the challan is made', max_length=8),
        ),
        migrations.AddField(
            model_name='labourrate',
            name='pay_basis',
            field=models.CharField(choices=[('accepted', 'Pieces accepted at QC'), ('received', 'Pieces received back')], default='accepted', help_text='Accepted: only pieces that pass QC are paid. Received: every piece that comes back is paid, rejected or not, and rework is paid at the rework rate alone.', max_length=8, verbose_name='Pay on'),
        ),
        migrations.AddField(
            model_name='qcresult',
            name='pay_qty',
            field=models.PositiveIntegerField(default=0, help_text="Pieces to pay for, fixed at QC from the challan's pay basis"),
        ),
        migrations.AlterField(
            model_name='dailysummaryrow',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the pieces checked today pay', max_digits=16),
        ),
        migrations.AlterField(
            model_name='historicaldailysummaryrow',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the pieces checked today pay', max_digits=16),
        ),
        migrations.AlterField(
            model_name='historicalqcresult',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate that applies to the pieces paid', max_digits=10),
        ),
        migrations.AlterField(
            model_name='qcresult',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate that applies to the pieces paid', max_digits=10),
        ),
        migrations.CreateModel(
            name='HistoricalJobWorkDeductionWaiver',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('waived_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receiptline')),
                ('receipt_trim', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobwork.receipttrim')),
                ('waived_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical job work deduction waiver',
                'verbose_name_plural': 'historical job work deduction waivers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JobWorkDeductionWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('waived_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiver', to='jobwork.receiptline')),
                ('receipt_trim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiver', to='jobwork.receipttrim')),
                ('waived_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('receipt_line__isnull', False), ('receipt_trim__isnull', True)), models.Q(('receipt_line__isnull', True), ('receipt_trim__isnull', False)), _connector='OR'), name='waiver_has_one_source')],
            },
        ),
    ]
