# Generated by Django 5.2.17 on 2026-10-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_seed_cogs_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.packinglist'),
        ),
    ]
